[programs.localnet]
test_pro = "4G8cUV1fv6SMrHw43D1ZC6WhtUwDNd6Wupj8bGcp9QXT"
to_do = "GXR9LC7XaAPhuPHh66K4Ny9nWqsC9kxMxDcFqXDwQMUo"
[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/Adam/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
